/** @type {import('tailwindcss').Config} */
export default {
  content: ["./src/**/*.{js,ts,jsx,tsx}"],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        background: '#F3F3F3',
        'dark-background': '#0A0A0A',
        surface: '#FFFFFF',
        'dark-surface': '#141414',
        'surface-container-low': '#f3f3f3',
        'surface-container': '#eeeeee',
        'surface-container-high': '#e8e8e8',
        'surface-container-highest': '#e2e2e2',
        'surface-variant': '#e2e2e2',
        'surface-bright': '#f9f9f9',
        'surface-dim': '#dadada',
        'on-surface': '#1b1b1b',
        'on-surface-variant': '#4c4546',
        'inverse-surface': '#303030',
        'inverse-on-surface': '#f1f1f1',
        'inverse-primary': '#c6c6c6',
        'surface-tint': '#5e5e5e',
        border: '#E5E5E5',
        'dark-border': '#2A2A2A',
        'canvas-line': '#E7E7E7',
        'dark-canvas-line': '#1F1F1F',
        outline: '#7e7576',
        'outline-variant': '#cfc4c5',
        primary: '#000000',
        'dark-primary': '#FFFFFF',
        'on-primary': '#ffffff',
        'primary-container': '#1b1b1b',
        'on-primary-container': '#848484',
        'primary-fixed': '#e2e2e2',
        'on-primary-fixed': '#1b1b1b',
        'primary-fixed-dim': '#c6c6c6',
        'on-primary-fixed-variant': '#474747',
        secondary: '#5e5e5e',
        'on-secondary': '#ffffff',
        'secondary-container': '#e1dfdf',
        'on-secondary-container': '#626263',
        'secondary-fixed': '#e4e2e2',
        'on-secondary-fixed': '#1b1c1c',
        'secondary-fixed-dim': '#c7c6c6',
        'on-secondary-fixed-variant': '#464747',
        tertiary: '#000000',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#1b1b1b',
        'on-tertiary-container': '#848484',
        'tertiary-fixed': '#e2e2e2',
        'on-tertiary-fixed': '#1b1b1b',
        'tertiary-fixed-dim': '#c6c6c6',
        'on-tertiary-fixed-variant': '#474747',
        error: '#EF4444',
        'dark-error': '#F87171',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        success: '#10B981',
        'dark-success': '#34D399',
        warning: '#F59E0B',
        'dark-warning': '#FBBF24',
        dropzone: '#EFEFEF',
        'dark-dropzone': '#1E1E1E',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        xs: '4px',
        sm: '8px',
        md: '16px',
        lg: '24px',
        xl: '32px',
        '2xl': '48px',
      },
      fontFamily: {
        'body-md': ['Plus Jakarta Sans', 'sans-serif'],
        'display-serif': ['Playfair Display', 'Instrument Serif', 'serif'],
        'headline-lg': ['Playfair Display', 'serif'],
        'sans-ui': ['Plus Jakarta Sans', 'Inter', 'Geist', 'sans-serif'],
        'mono-code': ['JetBrains Mono', 'Geist Mono', 'monospace'],
        'body-semibold': ['Plus Jakarta Sans', 'sans-serif'],
        'label-sm': ['Plus Jakarta Sans', 'sans-serif'],
        'headline-md': ['Playfair Display', 'serif'],
        'code-log': ['JetBrains Mono', 'monospace'],
      },
      fontSize: {
        'body-md': ['14px', { lineHeight: '1.5', fontWeight: '400' }],
        'headline-lg': ['30px', { lineHeight: '1.2', fontWeight: '600' }],
        'body-semibold': ['14px', { lineHeight: '1.5', fontWeight: '600' }],
        'label-sm': ['12px', { lineHeight: '1.4', fontWeight: '500' }],
        'headline-md': ['22px', { lineHeight: '1.3', fontWeight: '600' }],
        'code-log': ['12px', { lineHeight: '1.4', fontWeight: '400' }],
      },
    },
  },
  plugins: [],
}
